{"primaryContentSections":[{"kind":"content","content":[{"type":"paragraph","inlineContent":[{"type":"emphasis","inlineContent":[{"text":"Error handling","type":"text"}]},{"text":" is the process of responding to","type":"text"},{"text":" ","type":"text"},{"text":"and recovering from error conditions in your program.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Swift provides first-class support for"},{"type":"text","text":" "},{"text":"throwing, catching, propagating, and manipulating","type":"text"},{"type":"text","text":" "},{"type":"text","text":"recoverable errors at runtime."}]},{"inlineContent":[{"type":"text","text":"Some operations"},{"type":"text","text":" "},{"type":"text","text":"aren’t guaranteed to always complete execution or produce a useful output."},{"type":"text","text":" "},{"text":"Optionals are used to represent the absence of a value,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"but when an operation fails,"},{"type":"text","text":" "},{"type":"text","text":"it’s often useful to understand what caused the failure,"},{"text":" ","type":"text"},{"type":"text","text":"so that your code can respond accordingly."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"As an example, consider the task of reading and processing data from a file on disk."},{"type":"text","text":" "},{"type":"text","text":"There are a number of ways this task can fail, including"},{"type":"text","text":" "},{"type":"text","text":"the file not existing at the specified path,"},{"text":" ","type":"text"},{"type":"text","text":"the file not having read permissions, or"},{"text":" ","type":"text"},{"type":"text","text":"the file not being encoded in a compatible format."},{"text":" ","type":"text"},{"text":"Distinguishing among these different situations","type":"text"},{"type":"text","text":" "},{"text":"allows a program to resolve some errors","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and to communicate to the user any errors it can’t resolve."}],"type":"paragraph"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"Error handling in Swift interoperates with error handling patterns"},{"type":"text","text":" "},{"type":"text","text":"that use the "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" class in Cocoa and Objective-C."},{"text":" ","type":"text"},{"type":"text","text":"For more information about this class,"},{"type":"text","text":" "},{"type":"text","text":"see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","style":"note"},{"type":"heading","text":"Representar y arrojar errores","level":2,"anchor":"Representar-y-arrojar-errores"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift, errors are represented by"},{"type":"text","text":" "},{"type":"text","text":"values of types that conform to the "},{"type":"codeVoice","code":"Error"},{"text":" protocol.","type":"text"},{"type":"text","text":" "},{"text":"This empty protocol indicates that a type","type":"text"},{"text":" ","type":"text"},{"text":"can be used for error handling.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Swift enumerations are particularly well suited to modeling"},{"text":" ","type":"text"},{"type":"text","text":"a group of related error conditions,"},{"text":" ","type":"text"},{"type":"text","text":"with associated values allowing for additional information"},{"type":"text","text":" "},{"text":"about the nature of an error to be communicated.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, here’s how you might represent the error conditions"},{"type":"text","text":" "},{"type":"text","text":"of operating a vending machine inside a game:"}]},{"syntax":"swift","type":"codeListing","code":["enum VendingMachineError: Error {","    case invalidSelection","    case insufficientFunds(coinsNeeded: Int)","    case outOfStock","}"]},{"type":"paragraph","inlineContent":[{"text":"Throwing an error lets you indicate that something unexpected happened","type":"text"},{"text":" ","type":"text"},{"text":"and the normal flow of execution can’t continue.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You use a "},{"code":"throw","type":"codeVoice"},{"type":"text","text":" statement to throw an error."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"text":" ","type":"text"},{"type":"text","text":"the following code throws an error to indicate"},{"type":"text","text":" "},{"type":"text","text":"that five additional coins are needed by the vending machine:"}]},{"code":["throw VendingMachineError.insufficientFunds(coinsNeeded: 5)"],"syntax":"swift","type":"codeListing"},{"level":2,"type":"heading","anchor":"Manejo-de-errores","text":"Manejo de errores"},{"inlineContent":[{"type":"text","text":"When an error is thrown,"},{"type":"text","text":" "},{"text":"some surrounding piece of code must be responsible","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for handling the error —"},{"text":" ","type":"text"},{"type":"text","text":"for example, by correcting the problem,"},{"text":" ","type":"text"},{"type":"text","text":"trying an alternative approach,"},{"type":"text","text":" "},{"type":"text","text":"or informing the user of the failure."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are four ways to handle errors in Swift."},{"type":"text","text":" "},{"type":"text","text":"You can propagate the error from a function to the code that calls that function,"},{"type":"text","text":" "},{"text":"handle the error using a ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement,"},{"type":"text","text":" "},{"type":"text","text":"handle the error as an optional value,"},{"text":" ","type":"text"},{"type":"text","text":"or assert that the error will not occur."},{"text":" ","type":"text"},{"type":"text","text":"Each approach is described in a section below."}]},{"type":"paragraph","inlineContent":[{"text":"When a function throws an error,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"it changes the flow of your program,"},{"text":" ","type":"text"},{"text":"so it’s important that you can quickly identify places in your code that can throw errors.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To identify these places in your code, write the "},{"code":"try","type":"codeVoice"},{"text":" keyword —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or the "},{"type":"codeVoice","code":"try?"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"try!"},{"type":"text","text":" variation —"},{"type":"text","text":" "},{"text":"before a piece of code that calls a function, method, or initializer that can throw an error.","type":"text"},{"type":"text","text":" "},{"text":"These keywords are described in the sections below.","type":"text"}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Error handling in Swift resembles exception handling in other languages,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with the use of the "},{"type":"codeVoice","code":"try"},{"type":"text","text":", "},{"code":"catch","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"throw","type":"codeVoice"},{"type":"text","text":" keywords."},{"type":"text","text":" "},{"type":"text","text":"Unlike exception handling in many languages —"},{"text":" ","type":"text"},{"type":"text","text":"including Objective-C —"},{"text":" ","type":"text"},{"text":"error handling in Swift doesn’t involve unwinding the call stack,","type":"text"},{"type":"text","text":" "},{"text":"a process that can be computationally expensive.","type":"text"},{"type":"text","text":" "},{"text":"As such, the performance characteristics","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of a "},{"code":"throw","type":"codeVoice"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"text":"are comparable to those of a ","type":"text"},{"type":"codeVoice","code":"return"},{"text":" statement.","type":"text"}]}],"type":"aside","name":"Note"},{"type":"heading","text":"Propagación de errores mediante funciones que arrojan errores","anchor":"Propagaci%C3%B3n-de-errores-mediante-funciones-que-arrojan-errores","level":3},{"inlineContent":[{"text":"To indicate that a function, method, or initializer can throw an error,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"you write the "},{"code":"throws","type":"codeVoice"},{"type":"text","text":" keyword in the function’s declaration"},{"type":"text","text":" "},{"type":"text","text":"after its parameters."},{"type":"text","text":" "},{"type":"text","text":"A function marked with "},{"code":"throws","type":"codeVoice"},{"type":"text","text":" is called a "},{"type":"emphasis","inlineContent":[{"type":"text","text":"throwing function"}]},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"If the function specifies a return type,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"type":"codeVoice","code":"throws"},{"type":"text","text":" keyword before the return arrow ("},{"code":"->","type":"codeVoice"},{"text":").","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func canThrowErrors() throws -> String","","func cannotThrowErrors() -> String"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A throwing function propagates errors that are thrown inside of it"},{"type":"text","text":" "},{"type":"text","text":"to the scope from which it’s called."}]},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"Only throwing functions can propagate errors."},{"text":" ","type":"text"},{"type":"text","text":"Any errors thrown inside a nonthrowing function"},{"text":" ","type":"text"},{"type":"text","text":"must be handled inside the function."}],"type":"paragraph"}],"name":"Note","type":"aside"},{"type":"paragraph","inlineContent":[{"text":"In the example below,","type":"text"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"type":"codeVoice","code":"VendingMachine"},{"type":"text","text":" class has a "},{"code":"vend(itemNamed:)","type":"codeVoice"},{"type":"text","text":" method"},{"type":"text","text":" "},{"text":"that throws an appropriate ","type":"text"},{"code":"VendingMachineError","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"if the requested item isn’t available,"},{"type":"text","text":" "},{"type":"text","text":"is out of stock,"},{"type":"text","text":" "},{"text":"or has a cost that exceeds the current deposited amount:","type":"text"}]},{"code":["struct Item {","    var price: Int","    var count: Int","}","","class VendingMachine {","    var inventory = [","        \"Candy Bar\": Item(price: 12, count: 7),","        \"Chips\": Item(price: 10, count: 4),","        \"Pretzels\": Item(price: 7, count: 11)","    ]","    var coinsDeposited = 0","","    func vend(itemNamed name: String) throws {","        guard let item = inventory[name] else {","            throw VendingMachineError.invalidSelection","        }","","        guard item.count > 0 else {","            throw VendingMachineError.outOfStock","        }","","        guard item.price <= coinsDeposited else {","            throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)","        }","","        coinsDeposited -= item.price","","        var newItem = item","        newItem.count -= 1","        inventory[name] = newItem","","        print(\"Dispensing \\(name)\")","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The implementation of the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"text":" method","type":"text"},{"type":"text","text":" "},{"text":"uses ","type":"text"},{"type":"codeVoice","code":"guard"},{"text":" statements to exit the method early and throw appropriate errors","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if any of the requirements for purchasing a snack aren’t met."},{"type":"text","text":" "},{"type":"text","text":"Because a "},{"code":"throw","type":"codeVoice"},{"type":"text","text":" statement immediately transfers program control,"},{"text":" ","type":"text"},{"type":"text","text":"an item will be vended only if all of these requirements are met."}]},{"inlineContent":[{"text":"Because the ","type":"text"},{"code":"vend(itemNamed:)","type":"codeVoice"},{"type":"text","text":" method propagates any errors it throws,"},{"type":"text","text":" "},{"type":"text","text":"any code that calls this method must either handle the errors —"},{"text":" ","type":"text"},{"text":"using a ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"text":" statement, ","type":"text"},{"type":"codeVoice","code":"try?"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"try!"},{"type":"text","text":"—"},{"text":" ","type":"text"},{"type":"text","text":"or continue to propagate them."},{"type":"text","text":" "},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"code":"buyFavoriteSnack(person:vendingMachine:)","type":"codeVoice"},{"text":" in the example below","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is also a throwing function,"},{"text":" ","type":"text"},{"text":"and any errors that the ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method throws will"},{"text":" ","type":"text"},{"text":"propagate up to the point where the ","type":"text"},{"code":"buyFavoriteSnack(person:vendingMachine:)","type":"codeVoice"},{"text":" function is called.","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["let favoriteSnacks = [","    \"Alice\": \"Chips\",","    \"Bob\": \"Licorice\",","    \"Eve\": \"Pretzels\",","]","func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {","    let snackName = favoriteSnacks[person] ?? \"Candy Bar\"","    try vendingMachine.vend(itemNamed: snackName)","}"]},{"inlineContent":[{"text":"In this example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"code":"buyFavoriteSnack(person: vendingMachine:)","type":"codeVoice"},{"type":"text","text":" function looks up a given person’s favorite snack"},{"text":" ","type":"text"},{"text":"and tries to buy it for them by calling the ","type":"text"},{"code":"vend(itemNamed:)","type":"codeVoice"},{"type":"text","text":" method."},{"type":"text","text":" "},{"type":"text","text":"Because the "},{"code":"vend(itemNamed:)","type":"codeVoice"},{"type":"text","text":" method can throw an error,"},{"type":"text","text":" "},{"type":"text","text":"it’s called with the "},{"code":"try","type":"codeVoice"},{"text":" keyword in front of it.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Throwing initializers can propagate errors in the same way as throwing functions."},{"type":"text","text":" "},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the initializer for the "},{"type":"codeVoice","code":"PurchasedSnack"},{"text":" structure in the listing below","type":"text"},{"type":"text","text":" "},{"type":"text","text":"calls a throwing function as part of the initialization process,"},{"text":" ","type":"text"},{"type":"text","text":"and it handles any errors that it encounters by propagating them to its caller."}]},{"syntax":"swift","code":["struct PurchasedSnack {","    let name: String","    init(name: String, vendingMachine: VendingMachine) throws {","        try vendingMachine.vend(itemNamed: name)","        self.name = name","    }","}"],"type":"codeListing"},{"text":"Manejo de errores mediante do-catch","type":"heading","level":3,"anchor":"Manejo-de-errores-mediante-do-catch"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use a "},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement to handle errors"},{"type":"text","text":" "},{"text":"by running a block of code.","type":"text"},{"text":" ","type":"text"},{"text":"If an error is thrown by the code in the ","type":"text"},{"code":"do","type":"codeVoice"},{"text":" clause,","type":"text"},{"type":"text","text":" "},{"text":"it’s matched against the ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses"},{"text":" ","type":"text"},{"text":"to determine which one of them can handle the error.","type":"text"}]},{"inlineContent":[{"text":"Here is the general form of a ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["do {","    try <#expression#>","    <#statements#>","} catch <#pattern 1#> {","    <#statements#>","} catch <#pattern 2#> where <#condition#> {","    <#statements#>","} catch <#pattern 3#>, <#pattern 4#> where <#condition#> {","    <#statements#>","} catch {","    <#statements#>","}"]},{"inlineContent":[{"type":"text","text":"You write a pattern after "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" to indicate what errors"},{"type":"text","text":" "},{"text":"that clause can handle.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If a "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause doesn’t have a pattern,"},{"type":"text","text":" "},{"text":"the clause matches any error","type":"text"},{"type":"text","text":" "},{"text":"and binds the error to a local constant named ","type":"text"},{"type":"codeVoice","code":"error"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"For more information about pattern matching,"},{"text":" ","type":"text"},{"text":"see ","type":"text"},{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, the following code matches against all three cases"},{"type":"text","text":" "},{"text":"of the ","type":"text"},{"type":"codeVoice","code":"VendingMachineError"},{"text":" enumeration.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["var vendingMachine = VendingMachine()","vendingMachine.coinsDeposited = 8","do {","    try buyFavoriteSnack(person: \"Alice\", vendingMachine: vendingMachine)","    print(\"Success! Yum.\")","} catch VendingMachineError.invalidSelection {","    print(\"Invalid Selection.\")","} catch VendingMachineError.outOfStock {","    print(\"Out of Stock.\")","} catch VendingMachineError.insufficientFunds(let coinsNeeded) {","    print(\"Insufficient funds. Please insert an additional \\(coinsNeeded) coins.\")","} catch {","    print(\"Unexpected error: \\(error).\")","}","\/\/ Prints \"Insufficient funds. Please insert an additional 2 coins.\""]},{"type":"paragraph","inlineContent":[{"text":"In the above example,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the "},{"code":"buyFavoriteSnack(person:vendingMachine:)","type":"codeVoice"},{"text":" function is called in a ","type":"text"},{"type":"codeVoice","code":"try"},{"text":" expression,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"because it can throw an error."},{"type":"text","text":" "},{"type":"text","text":"If an error is thrown,"},{"text":" ","type":"text"},{"type":"text","text":"execution immediately transfers to the "},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses,"},{"type":"text","text":" "},{"type":"text","text":"which decide whether to allow propagation to continue."},{"type":"text","text":" "},{"text":"If no pattern is matched, the error gets caught by the final ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" "},{"type":"text","text":"clause and is bound to a local "},{"type":"codeVoice","code":"error"},{"type":"text","text":" constant."},{"text":" ","type":"text"},{"type":"text","text":"If no error is thrown,"},{"type":"text","text":" "},{"text":"the remaining statements in the ","type":"text"},{"code":"do","type":"codeVoice"},{"type":"text","text":" statement are executed."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"catch","type":"codeVoice"},{"text":" clauses don’t have to handle every possible error","type":"text"},{"type":"text","text":" "},{"text":"that the code in the ","type":"text"},{"type":"codeVoice","code":"do"},{"text":" clause can throw.","type":"text"},{"text":" ","type":"text"},{"text":"If none of the ","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" clauses handle the error,","type":"text"},{"type":"text","text":" "},{"text":"the error propagates to the surrounding scope.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"However, the propagated error"},{"text":" ","type":"text"},{"text":"must be handled by ","type":"text"},{"inlineContent":[{"text":"some","type":"text"}],"type":"emphasis"},{"text":" surrounding scope.","type":"text"},{"type":"text","text":" "},{"text":"In a nonthrowing function,","type":"text"},{"text":" ","type":"text"},{"text":"an enclosing ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement"},{"text":" ","type":"text"},{"type":"text","text":"must handle the error."},{"type":"text","text":" "},{"text":"In a throwing function,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"either an enclosing "},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"or the caller"},{"type":"text","text":" "},{"type":"text","text":"must handle the error."},{"type":"text","text":" "},{"type":"text","text":"If the error propagates to the top-level scope"},{"text":" ","type":"text"},{"type":"text","text":"without being handled,"},{"text":" ","type":"text"},{"text":"you’ll get a runtime error.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"For example, the above example can be written so any","type":"text"},{"type":"text","text":" "},{"type":"text","text":"error that isn’t a "},{"type":"codeVoice","code":"VendingMachineError"},{"text":" is instead","type":"text"},{"type":"text","text":" "},{"type":"text","text":"caught by the calling function:"}]},{"code":["func nourish(with item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch is VendingMachineError {","        print(\"Couldn't buy that from the vending machine.\")","    }","}","","do {","    try nourish(with: \"Beet-Flavored Chips\")","} catch {","    print(\"Unexpected non-vending-machine-related error: \\(error)\")","}","\/\/ Prints \"Couldn't buy that from the vending machine.\""],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"In the ","type":"text"},{"type":"codeVoice","code":"nourish(with:)"},{"text":" function,","type":"text"},{"text":" ","type":"text"},{"text":"if ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" throws an error that’s"},{"type":"text","text":" "},{"type":"text","text":"one of the cases of the "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" enumeration,"},{"text":" ","type":"text"},{"code":"nourish(with:)","type":"codeVoice"},{"type":"text","text":" handles the error by printing a message."},{"text":" ","type":"text"},{"text":"Otherwise,","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" propagates the error to its call site."},{"text":" ","type":"text"},{"text":"The error is then caught by the general ","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" clause.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Another way to catch several related errors"},{"type":"text","text":" "},{"text":"is to list them after ","type":"text"},{"code":"catch","type":"codeVoice"},{"type":"text","text":", separated by commas."},{"type":"text","text":" "},{"type":"text","text":"For example:"}]},{"syntax":"swift","type":"codeListing","code":["func eat(item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch VendingMachineError.invalidSelection, VendingMachineError.insufficientFunds, VendingMachineError.outOfStock {","        print(\"Invalid selection, out of stock, or not enough money.\")","    }","}"]},{"inlineContent":[{"type":"text","text":"The "},{"code":"eat(item:)","type":"codeVoice"},{"type":"text","text":" function lists the vending machine errors to catch,"},{"type":"text","text":" "},{"type":"text","text":"and its error text corresponds to the items in that list."},{"text":" ","type":"text"},{"type":"text","text":"If any of the three listed errors are thrown,"},{"type":"text","text":" "},{"type":"text","text":"this "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause handles them by printing a message."},{"text":" ","type":"text"},{"text":"Any other errors are propagated to the surrounding scope,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"including any vending-machine errors that might be added later."}],"type":"paragraph"},{"type":"heading","text":"Conversión de errores en valores opcionales","anchor":"Conversi%C3%B3n-de-errores-en-valores-opcionales","level":3},{"inlineContent":[{"type":"text","text":"You use "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" to handle an error by converting it to an optional value."},{"text":" ","type":"text"},{"type":"text","text":"If an error is thrown while evaluating the "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" expression,"},{"type":"text","text":" "},{"type":"text","text":"the value of the expression is "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in the following code "},{"code":"x","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"y"},{"text":" have the same value and behavior:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["func someThrowingFunction() throws -> Int {","    \/\/ ...","}","","let x = try? someThrowingFunction()","","let y: Int?","do {","    y = try someThrowingFunction()","} catch {","    y = nil","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"code":"someThrowingFunction()","type":"codeVoice"},{"type":"text","text":" throws an error,"},{"type":"text","text":" "},{"text":"the value of ","type":"text"},{"code":"x","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" is "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Otherwise, the value of "},{"type":"codeVoice","code":"x"},{"text":" and ","type":"text"},{"code":"y","type":"codeVoice"},{"text":" is the value that the function returned.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note that "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" are an optional of whatever type "},{"type":"codeVoice","code":"someThrowingFunction()"},{"text":" returns.","type":"text"},{"type":"text","text":" "},{"text":"Here the function returns an integer, so ","type":"text"},{"code":"x","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" are optional integers."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" lets you write concise error handling code"},{"type":"text","text":" "},{"text":"when you want to handle all errors in the same way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"type":"text","text":"the following code"},{"type":"text","text":" "},{"type":"text","text":"uses several approaches to fetch data,"},{"text":" ","type":"text"},{"text":"or returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all of the approaches fail."}]},{"code":["func fetchData() -> Data? {","    if let data = try? fetchDataFromDisk() { return data }","    if let data = try? fetchDataFromServer() { return data }","    return nil","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Inhabilitar la propagación de errores","level":3,"anchor":"Inhabilitar-la-propagaci%C3%B3n-de-errores"},{"inlineContent":[{"text":"Sometimes you know a throwing function or method","type":"text"},{"type":"text","text":" "},{"type":"text","text":"won’t, in fact, throw an error at runtime."},{"text":" ","type":"text"},{"text":"On those occasions,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you can write "},{"type":"codeVoice","code":"try!"},{"type":"text","text":" before the expression to disable error propagation"},{"text":" ","type":"text"},{"type":"text","text":"and wrap the call in a runtime assertion that no error will be thrown."},{"type":"text","text":" "},{"text":"If an error actually is thrown, you’ll get a runtime error.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"For example, the following code uses a ","type":"text"},{"code":"loadImage(atPath:)","type":"codeVoice"},{"type":"text","text":" function,"},{"type":"text","text":" "},{"type":"text","text":"which loads the image resource at a given path"},{"text":" ","type":"text"},{"text":"or throws an error if the image can’t be loaded.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In this case, because the image is shipped with the application,"},{"text":" ","type":"text"},{"text":"no error will be thrown at runtime,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so it’s appropriate to disable error propagation."}]},{"type":"codeListing","syntax":"swift","code":["let photo = try! loadImage(atPath: \".\/Resources\/John Appleseed.jpg\")"]},{"anchor":"Especificando-acciones-de-limpieza","type":"heading","level":2,"text":"Especificando acciones de limpieza"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use a "},{"code":"defer","type":"codeVoice"},{"text":" statement to execute a set of statements","type":"text"},{"type":"text","text":" "},{"text":"just before code execution leaves the current block of code.","type":"text"},{"text":" ","type":"text"},{"text":"This statement lets you do any necessary cleanup","type":"text"},{"type":"text","text":" "},{"text":"that should be performed regardless","type":"text"},{"type":"text","text":" "},{"text":"of ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"how","type":"text"}]},{"text":" execution leaves the current block of code —","type":"text"},{"type":"text","text":" "},{"text":"whether it leaves because an error was thrown","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or because of a statement such as "},{"type":"codeVoice","code":"return"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"break"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"For example, you can use a ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" statement","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to ensure that file descriptors are closed"},{"type":"text","text":" "},{"text":"and manually allocated memory is freed.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" statement defers execution until the current scope is exited.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This statement consists of the "},{"type":"codeVoice","code":"defer"},{"text":" keyword and the statements to be executed later.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The deferred statements may not contain any code"},{"type":"text","text":" "},{"type":"text","text":"that would transfer control out of the statements,"},{"type":"text","text":" "},{"type":"text","text":"such as a "},{"type":"codeVoice","code":"break"},{"type":"text","text":" or a "},{"code":"return","type":"codeVoice"},{"type":"text","text":" statement,"},{"type":"text","text":" "},{"type":"text","text":"or by throwing an error."},{"type":"text","text":" "},{"text":"Deferred actions are executed in the reverse of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the order that they’re written in your source code."},{"type":"text","text":" "},{"type":"text","text":"That is, the code in the first "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement executes last,"},{"type":"text","text":" "},{"type":"text","text":"the code in the second "},{"code":"defer","type":"codeVoice"},{"text":" statement executes second to last,","type":"text"},{"type":"text","text":" "},{"text":"and so on.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The last "},{"type":"codeVoice","code":"defer"},{"text":" statement in source code order executes first.","type":"text"}]},{"type":"codeListing","code":["func processFile(filename: String) throws {","    if exists(filename) {","        let file = open(filename)","        defer {","            close(file)","        }","        while let line = try file.readline() {","            \/\/ Work with the file.","        }","        \/\/ close(file) is called here, at the end of the scope.","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The above example uses a "},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"to ensure that the "},{"code":"open(_:)","type":"codeVoice"},{"text":" function","type":"text"},{"text":" ","type":"text"},{"text":"has a corresponding call to ","type":"text"},{"code":"close(_:)","type":"codeVoice"},{"text":".","type":"text"}]},{"content":[{"inlineContent":[{"text":"You can use a ","type":"text"},{"code":"defer","type":"codeVoice"},{"text":" statement","type":"text"},{"type":"text","text":" "},{"type":"text","text":"even when no error handling code is involved."}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"},{"name":"Software Beta","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""}]},{"inlineContent":[{"type":"text","text":"Esta documentación contiene información preliminar sobre una API o tecnología en desarrollo. Esta información está sujeta a cambios, y todo software implementado en conformidad con esta documentación debe ser testeado con el software final del sistema operativo."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Conoce más acerca del uso del "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/es\/support\/beta-software\/","isActive":true},{"type":"text","text":"."}]}],"type":"aside"}]}],"identifier":{"url":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ErrorHandling","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"Manejo de errores"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language"]]},"abstract":[{"text":"Respond to and recover from errors.","type":"text"}],"references":{"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/Patterns":{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","type":"topic","title":"Patrones","kind":"article","role":"article","abstract":[{"type":"text","text":"Match and destructure values."}],"url":"\/documentation\/the-swift-programming-language\/patterns"},"https://developer.apple.com/documentation/swift/cocoa_design_patterns/handling_cocoa_errors_in_swift":{"title":"Handling Cocoa Errors in Swift","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","titleInlineContent":[{"type":"text","text":"Handling Cocoa Errors in Swift"}],"url":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","type":"link"},"https://developer.apple.com/es/support/beta-software/":{"title":"software beta de Apple","identifier":"https:\/\/developer.apple.com\/es\/support\/beta-software\/","titleInlineContent":[{"type":"text","text":"software beta de Apple"}],"url":"https:\/\/developer.apple.com\/es\/support\/beta-software\/","type":"link"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language":{"title":"The Swift Programming Language (5.9)","kind":"article","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language","type":"topic","url":"\/documentation\/the-swift-programming-language","abstract":[],"role":"collection"}}}